### ISSUE TITLE
Need a good setup for tests

### ISSUE THREAD

**Issue by megoth** [RubenVerborgh/solid-server-ts#1]
Right now we have a lot of integration tests in [node-solid-server](https://github.com/solid/node-solid-server), some which requires a lot of setup (I think I'm on one of the worst cases now, with ~100 lines of code before I getting my first test working properly).

I know this is in consideration already, just wanted to make this issue to drill down the point that we need a good setup for tests on this server ^_^

**Comment by RubenVerborgh** [comment]
Indeed. Good testability comes from the ability to inject mock objects well.

The rule of thumb is that, to test classes with a lot of dependencies, there will be some initialization required—but it should not be for the others (and that's where node-solid-server goes wrong). For instance, we have these lengthy setups here:
- https://github.com/RubenVerborgh/solid-server-ts/blob/05c8955c4e25abb02e68771e15f9354b70dc3a9c/test/unit/http/ResourceStoreRequestHandler.ts#L17-L80
- https://github.com/RubenVerborgh/solid-server-ts/blob/05c8955c4e25abb02e68771e15f9354b70dc3a9c/test/integration/resource-store.ts#L16-L65

Note the difference between unit (mocks) and integration (real objects).

Quite a bit of that code will actually disappear if we have real implementations of all dependencies, because then we can auto-mock them. (We can mock TypeScript classes, but not interfaces.)

However, this is the initialization code for the most complex component in the entire codebase (which is also the reason why I wrote it upfront). And that preparation makes the individual tests very easy:

- https://github.com/RubenVerborgh/solid-server-ts/blob/05c8955c4e25abb02e68771e15f9354b70dc3a9c/test/integration/resource-store.ts#L68
- https://github.com/RubenVerborgh/solid-server-ts/blob/05c8955c4e25abb02e68771e15f9354b70dc3a9c/test/unit/http/ResourceStoreRequestHandler.ts#L83-L85

In contrast to node-solid-server, where everything depends on each other, simple components can be tested with no or very limited setup:
- https://github.com/RubenVerborgh/solid-server-ts/blob/05c8955c4e25abb02e68771e15f9354b70dc3a9c/test/unit/http/MethodExtractor.ts
- https://github.com/RubenVerborgh/solid-server-ts/blob/05c8955c4e25abb02e68771e15f9354b70dc3a9c/test/unit/http/TargetExtractor.ts
- https://github.com/RubenVerborgh/solid-server-ts/blob/05c8955c4e25abb02e68771e15f9354b70dc3a9c/test/unit/ldp/operations/LdpOperation.ts
- https://github.com/RubenVerborgh/solid-server-ts/blob/05c8955c4e25abb02e68771e15f9354b70dc3a9c/test/unit/ldp/operations/GetOperation.ts
